edition = "2021"
chain_width = 100
max_width = 120
hard_tabs = true
newline_style = "Unix"
reorder_imports = false
reorder_modules = false
use_try_shorthand = true
fn_args_layout = "Compressed"
use_field_init_shorthand = true
match_block_trailing_comma = true